version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend-container
    # ports:
    #   - 80:8080 # localport:dockerport
    # volumes:
    #   - ./:/app
