# Dev Containerではこちらが優先される。
services:
  backend: # fixme
    build:
      target: devcontainer
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend-container
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。
