# Dev Containerではこちらが優先される。
services:
  backend: # fixme
    build:
      target: devcontainer
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend-container
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。
services:
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: meetsphere-frontend:latest
    container_name: meetsphere-frontend-container
    ports:
      - 80:8080 # localport:dockerport

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: meetsphere-backend:latest
    container_name: meetsphere-backend-container
    ports:
      - 3000:3000 # localport:dockerport
